### ISSUE TITLE
Browser implementation of gRPC with Go backend?

### ISSUE THREAD

**Issue by emailtovamos** [grpc-ecosystem/awesome-grpc#26]
I want to create an html/javascript service which connects to a Go backend through gRPC. Is it possibe? Since I couldn't find any example that does this. 

For example, I have a small javascript game, and certain game related calculations/storage can be done on the Go backend and they communicate through gRPC.

**Comment by bojand** [comment]
The story around this is somewhat complicated. At the moment it usually it involves a proxy that the client will talk to. Please see [grpc/grpc-web](https://github.com/grpc/grpc-web) and [improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web). Also this [blog series](https://jbrandhorst.com/post/gopherjs-grpcweb/) may be of help along with the video [Creating GopherJS Apps with gRPC-Web ](https://www.youtube.com/watch?v=R2HaxH7Et64).
