### ISSUE TITLE
Consider moving to grpc-ecosystem org?

### ISSUE THREAD

**Issue by hsaliak** [grpc-ecosystem/awesome-grpc#5]
@bojand not sure how to contact you so I am filing this as an issue instead. 
Thanks for maintaining this list! I wanted to see if you would consider moving this to the grpc-ecosystem org - https://github.com/grpc-ecosystem/ . We would of course set you up with ownership of the repository. 

https://grpc.io/community/ has more details on what's involved and contributing guidelines (you do not need to fill up the request form, but would have to be OK with the guidelines). 

Also, is it ok for us (grpc) to link to this project from grpc.io? We are hopeful that we can do this, independent of your decision to move to this repo to the grpc-ecosystem org.

**Comment by bojand** [comment]
Hello, thanks for reaching out. I think moving the repository to grpc-ecosystem org, and linking to it from the official website would be useful for the gRPC community. Both ideas are agreeable to me as you've suggested them here. I am with limited internet access and without a computer until Thursday of next week; but I can sign the CLA and we can facilitate the transfer then.

**Comment by hsaliak** [comment]
@bojand thanks, that sounds good, I will give you the permissions in the the grpc-ecosystem org after you sign the CLA so you can transfer the repo over. 
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/ 
Once you do that, you will continue to have full ownership of the repo, and hopefully, more pull requests from others!

**Comment by bojand** [comment]
Hello, I have signed the CLA.

**Comment by hsaliak** [comment]
@bojand i've invited you to a team in the grpc-ecosystem repo. Once you accept that, you should have permissions to transfer the repo. Let me know if you run into any trouble with that. Of course, back up before you do! :)

**Comment by bojand** [comment]
@hsaliak Thanks for adding me to the grpc-ecosystem organization. I tried transferring the repo but I got an error:

> You don’t have the permission to create repositories on grpc-ecosystem 

From the [GitHub docs](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/):

> Users must have repository creation permissions within the receiving organization before they can transfer a repository that they individually own. If Allow members to create repositories for this organization has been disabled in the receiving organization, only organization owners can transfer repositories into the organization.

Maybe something is not setup 100% correctly. Let me know how to proceed and if this can be accommodated via org permissions. Otherwise I imagine we can work around by transferring the repo to your personal account and then you could transfer to the ecosystem. I looked into adding you as a collaborator to this repo, but that would help as only repo owners can transfer repos.

Thanks!

**Comment by hsaliak** [comment]
So that option is disabled, but the other option - allow members to transfer repositories is enabled. 
I think I misunderstood what that knob did, perhaps one is to accept the other is to transfer out.

In any case, can you try again?

**Comment by bojand** [comment]
@hsaliak Hello it seems to have worked now! I also checked and I was able to make a commit. Thanks!

I'll let you close the the issue when you feel appropriate. Either now or when it's linked from the official website if that's still the plan.

**Comment by hsaliak** [comment]
That’s definitely the plan - we will link it and encourage folks to
contribute as well!
Btw the license is in public domain - would you be open to switching it to
Apache?

**Comment by bojand** [comment]
I think normally software / code licenses are not recommended for content like awesome lists, but personally I do not have an objection. I have create a pull request #6.

**Comment by hsaliak** [comment]
Yes, that was my consideration as well. Let's hold of on this.. I'll come
back to you with a recommendation on what we can do.

**Comment by hsaliak** [comment]
@bojand following up on this - before we can submit patches, could you please re-license to https://creativecommons.org/licenses/by/4.0/ ? CC-BY license will work for us.

**Comment by bojand** [comment]
@hsaliak thanks for the follow up. Addressed in #9. Feel free to close this issue if everything is satisfactory. Thanks for your assistance with everything.

**Comment by hsaliak** [comment]
@bojand thankd for doing that! Can I also trouble you to add a LICENSE file https://help.github.com/articles/adding-a-license-to-a-repository/ with the license text?
Thanks for accommodating all the requests!

**Comment by bojand** [comment]
@hsaliak see PR #10 

I followed instructions as detailed in this [CC blog article](https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/). It states that the copyright notice line is optional so wasn't sure what to include there. Please let me know if the proposed license file is appropriate as is or what changes should be made.

**Comment by bojand** [comment]
Set the complete plaintext and merged the PR.
